import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "./(components)/Nav";
// import config from "@fortawesome/free-solid-svg-icons";
// import "@fortawesome/free-solid-svg-icons/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <div className="flex-grow overflow-y-auto bg-page text-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
